spring.datasource.url=jdbc:mysql://localhost:3306/vaultsync_db
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8081